version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    groups:
      artifact-io:
        patterns:
          - actions/*

  - package-ecosystem: "cargo"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    groups:
      kube:
        patterns:
          - kube
          - k8s-openapi
      otel:
        patterns:
          - tracing-opentelemetry
          - opentelemetry-otlp
          - opentelemetry_sdk
          - opentelemetry
          - tonic