---
apiVersion: replicator.yapp.example.com/v1alpha1
kind: SourceRepository
metadata:
  namespace: my-team
  labels:
    env: dev
    app: my-team-app
  name: my-team-app-promotion
spec:
  repository:
    name: myapp-docker-registry
    location: europe-west1
    format: Docker
    projectID: example-app-ci-a1
    Provider: GCP
    serviceAccount: example-app-ci-a1-service-account
