name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - ^issues\/[0-9]{1,2}(-[0-9]{1,2}?)$
    tags:
      - '*'

env:
  RUST_TOOLCHAIN: nightly

jobs:
  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt,clippy

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: musl-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings -W clippy::pedantic -W clippy::nursery -W rust-2018-idioms


  lint:
    needs: [clippy]
    name: Run Pedantic Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: musl-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt,clippy
      - run: cargo +${{ env.RUST_TOOLCHAIN }} fmt -- --check

      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --all-features

  test:
    needs : [clippy]
    name: Run Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt,clippy

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: musl-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --all

  crdgen:
    needs : [clippy]
    name: CRD Generator
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt,clippy

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: musl-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args:

      - uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test generate crds
        run: just generate

      - name: Output crd.yaml
        run: cat yaml/doc_crds/crd.yaml


  integration:
    needs: [lint, test, crdgen]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.25
          k3d-name: kube
          k3d-args: "--no-lb --no-rollback --k3s-arg --disable=traefik,servicelb,metrics-server@server:*"

      - name: Build workspace
        run: cargo build
      - name: Install crd
        run: cargo run --bin crdgen | kubectl apply -f -
      - name: Run all default features integration library tests
        # run: cargo test --core --all -- --ignored # TODO correct this so it only runs core tests
        run: cargo test --all -- --ignored


  docker-base:
    timeout-minutes: 10
    needs: [integration]
    runs-on: ubuntu-latest
    permissions:
      packages: write # for docker/build-push-action to push images
      id-token: write # for Cosign to be able to sign images with GHA token
    env:
      RUST_TOOLCHAIN: nightly
      IMAGE_NAME: ${{ github.repository_owner }}/yapp-controller
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: musl-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Build and push with docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Set build-time flags
        run: |
          echo "LDFLAGS=$(make echo-ldflags)" >> $GITHUB_ENV

      - name: Configure tags based on git tags + latest
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/casibbald/yapp-controller
          tags: |
            type=pep440,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=pr
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.title='YAPP Controller'
            org.opencontainers.image.description='Yet Another Pipeline Pusher'
            org.opencontainers.image.vendor='Acme Corporation'
            org.opencontainers.image.license='Apache-2.0'

      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: musl-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Compile base features
        run: |
          mkdir -p ~/.cargo/{git,registry}
          docker run --rm -t \
              --mount type=bind,source=${{ github.workspace }},target=/volume \
              --mount type=bind,source=$HOME/.cargo/registry,target=/root/.cargo/registry \
              --mount type=bind,source=$HOME/.cargo/git,target=/root/.cargo/git \
              clux/muslrust:${{ env.RUST_TOOLCHAIN }} \
              cargo build --release --bin yapp-controller
          cp target/x86_64-unknown-linux-musl/release/yapp-controller .

      - uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha,scope=base
          cache-to: type=gha,scope=base,mode=max
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - run: docker manifest inspect ghcr.io/casibbald/yapp-controller:latest

#      - name: Persist base image build to a tarball
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64/v8
#          tags: ${{ steps.meta.outputs.tags }}
#          cache-from: type=gha,scope=base
#          outputs: type=docker,dest=/tmp/image.tar
#
#      - name: Upload base docker image as artifact for e2e tests
#        uses: actions/upload-artifact@v4
#        with:
#          name: yapp-controller
#          path: /tmp/image.tar

  e2e:
    runs-on: ubuntu-latest
    needs: [ docker-base ]
    steps:
      - run: env
      - uses: actions/checkout@v4
      - uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.27
          k3d-name: kube
          k3d-args: "--no-lb --no-rollback --k3s-arg --disable=traefik,servicelb,metrics-server@server:*"
      - run: kubectl apply -f yaml/doc_crds/crd.yaml
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Download docker image artifact from docker job
#        uses: actions/download-artifact@v4
#        with:
#          name: yapp-controller
#          path: /tmp
#      - name: Load docker image from tarball
#        run: docker load --input /tmp/image.tar
      - name: helm template | kubctl apply
        run: |
          docker images casibbald/yapp-controller
          image_tag="$(docker images casibbald/yapp-controller | egrep 'yapp-controller' | awk '{print $2}' | head -1)"
          echo "image tag: ${image_tag}"
          apiserver="$(kubectl get endpoints kubernetes -ojson | jq '.subsets[0].addresses[0].ip' -r)"
          helm template charts/yapp-controller \
            --set version=latest \
            --set networkPolicy.enabled=true \
            --set networkPolicy.apiserver.0=${apiserver}/32 \
            --set image.repository=ghcr.io/casibbald/yapp-controller \
            --set image.tag=${image_tag} \
            | kubectl apply -f -
      - run: sleep 5
      - run: kubectl get events
      - run: kubectl get pods
      - run: kubectl describe deployment yapp-controller
      - run: kubectl describe pod $(kubectl get pods | egrep 'yap-controller' | awk '{print $1}')
      - run: kubectl logs $(kubectl get pods | egrep 'yapp-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
      - run: kubectl wait --for=condition=available deploy/yapp-controller --timeout=120s
      - run: kubectl logs deploy/yapp-controller
      - run: kubectl logs $(kubectl get pods | egrep 'yapp-controller' | awk '{print $1}' | head -1)
      - run: kubectl apply -f yaml/doc_crds/instance-samuel.yaml
      - run: sleep 2 # TODO: add condition on status and wait for it instead
      # verify reconcile actions have happened
      - run: kubectl get netpol yapp-controller -oyaml
      - run: kubectl logs deploy/yapp-controller
      - run: kubectl get event --field-selector "involvedObject.kind=Document,involvedObject.name=samuel" | grep "HideRequested"
      - run: kubectl get doc -oyaml | grep -A1 finalizers | grep documents.kube.rs
