# When pushed to master, run `cargo +nightly fmt --all` and open a PR.
name: rustfmt
on:
  pull_request:
  push:
    branches:
      - main
      - ^[0-9]{1,2}-.*$
    tags:
      - '*'
jobs:
  rustfmt_nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo +nightly fmt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: rustfmt
          signoff: true
          title: rustfmt
          body: Changes from `cargo +nightly fmt`.
          branch: rustfmt
          # Delete branch when merged
          delete-branch: true